### ISSUE TITLE
Game crashes after "Choose your heros!"

### ISSUE THREAD

**Issue by abgita** [SteveSmith16384/GangBeastsFPS#1]
**Steps to reproduce the error:**

1. Open jaroverblown-1.1.jar from itch.io
2. Press space
3. Click anywhere with the mouse
4. Press space three times

**Console log:**
```
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: couldn't compile shader: Fragment shader:
0:15(2): error: initializer of type int cannot be assigned to variable of type float
	at com.scs.splitscreenfps.game.decals.ShadedGroupStrategy.createDefaultShader(ShadedGroupStrategy.java:201)
	at com.scs.splitscreenfps.game.decals.ShadedGroupStrategy.<init>(ShadedGroupStrategy.java:118)
	at com.scs.splitscreenfps.game.decals.ShadedGroupStrategy.<init>(ShadedGroupStrategy.java:105)
	at com.scs.splitscreenfps.game.ViewportData.<init>(ViewportData.java:33)
	at com.scs.splitscreenfps.game.Game.<init>(Game.java:168)
	at com.scs.splitscreenfps.pregame.SelectHeroModule.startGame(SelectHeroModule.java:260)
	at com.scs.splitscreenfps.pregame.SelectHeroModule.render(SelectHeroModule.java:161)
	at com.scs.splitscreenfps.BillBoardFPS_Main.render(BillBoardFPS_Main.java:69)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by abgita** [comment]
## https://github.com/SteveSmith16384/OverblownGame/blob/a208d0ce3435366c706d61d7a789a538a45bcad5/core/assets/shaders/decal_fragment.glsl#L15

**Comment by SteveSmith16384** [comment]
Thanks for raising the issue.  I've run the game on several PCs and none seemed to have a problem.  

I don't suppose you're able to change the line to "float fog_density = 0.0;" to see if that fixes it for you?

**Comment by abgita** [comment]
Yes it works

**Comment by SteveSmith16384** [comment]
Thanks a lot.  I've updated the code, and the next release will have the fix.
